# Generated by Django 5.0.4 on 2024-04-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='about_the_company',
            field=models.TextField(default='real family sauce products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='about_the_company_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
