# Generated by Django 5.0.4 on 2024-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_partner_about_about_the_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='meta_description',
            field=models.TextField(default='sauce'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='meta_keywords',
            field=models.TextField(default='sauce'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='meta_title',
            field=models.TextField(default='sauce'),
            preserve_default=False,
        ),
    ]
